// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trafficService.proto

package grpc.trafficservice;

public interface AlertOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trafficservice.Alert)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
