// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trafficService.proto

package grpc.trafficservice;

public interface AreaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trafficservice.Area)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Dublin district area that the user wants info about (D01 to D24)
   * </pre>
   *
   * <code>int32 intArea = 1;</code>
   */
  int getIntArea();
}
