// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trafficService.proto

package grpc.trafficservice;

public interface AreaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trafficservice.Area)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messageArea = 1;</code>
   */
  java.lang.String getMessageArea();
  /**
   * <code>string messageArea = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageAreaBytes();
}
