// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trafficService.proto

package grpc.trafficservice;

public interface StreetSituationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trafficservice.StreetSituation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string textSituation = 1;</code>
   */
  java.lang.String getTextSituation();
  /**
   * <code>string textSituation = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextSituationBytes();
}
