// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trafficService.proto

package grpc.trafficservice;

public final class TrafficServiceImpl {
  private TrafficServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficservice_RequestEmergency_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficservice_RequestEmergency_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficservice_EmergencyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficservice_EmergencyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficservice_Area_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficservice_Area_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficservice_StreetSituation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficservice_StreetSituation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficservice_Video_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficservice_Video_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficservice_WarningResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficservice_WarningResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024trafficService.proto\022\016trafficservice\"#" +
      "\n\020RequestEmergency\022\017\n\007message\030\001 \001(\t\"!\n\021E" +
      "mergencyResponse\022\014\n\004text\030\001 \001(\t\"\027\n\004Area\022\017" +
      "\n\007intArea\030\001 \001(\005\"(\n\017StreetSituation\022\025\n\rte" +
      "xtSituation\030\001 \001(\t\"!\n\005Video\022\030\n\020pedestrian" +
      "Number\030\001 \001(\005\"\037\n\017WarningResponse\022\014\n\004text\030" +
      "\001 \001(\t2\202\002\n\016trafficService\022T\n\rsendEmergenc" +
      "y\022 .trafficservice.RequestEmergency\032!.tr" +
      "afficservice.EmergencyResponse\022C\n\010LiveFe" +
      "ed\022\024.trafficservice.Area\032\037.trafficservic" +
      "e.StreetSituation0\001\022U\n\031CalculatePedestri" +
      "anNumber\022\025.trafficservice.Video\032\037.traffi" +
      "cservice.WarningResponse(\001B+\n\023grpc.traff" +
      "icserviceB\022TrafficServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_trafficservice_RequestEmergency_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_trafficservice_RequestEmergency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficservice_RequestEmergency_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_trafficservice_EmergencyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_trafficservice_EmergencyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficservice_EmergencyResponse_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_trafficservice_Area_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_trafficservice_Area_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficservice_Area_descriptor,
        new java.lang.String[] { "IntArea", });
    internal_static_trafficservice_StreetSituation_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_trafficservice_StreetSituation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficservice_StreetSituation_descriptor,
        new java.lang.String[] { "TextSituation", });
    internal_static_trafficservice_Video_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_trafficservice_Video_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficservice_Video_descriptor,
        new java.lang.String[] { "PedestrianNumber", });
    internal_static_trafficservice_WarningResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_trafficservice_WarningResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficservice_WarningResponse_descriptor,
        new java.lang.String[] { "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
