// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trafficService.proto

package grpc.trafficservice;

public final class TrafficServiceImpl {
  private TrafficServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficservice_RequestEmergency_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficservice_RequestEmergency_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficservice_EmergencyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficservice_EmergencyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficservice_Area_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficservice_Area_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficservice_StreetSituation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficservice_StreetSituation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024trafficService.proto\022\016trafficservice\"#" +
      "\n\020RequestEmergency\022\017\n\007message\030\001 \001(\t\"!\n\021E" +
      "mergencyResponse\022\014\n\004text\030\001 \001(\t\"\027\n\004Area\022\017" +
      "\n\007intArea\030\001 \001(\005\"(\n\017StreetSituation\022\025\n\rte" +
      "xtSituation\030\001 \001(\t2\253\001\n\016trafficService\022T\n\r" +
      "sendEmergency\022 .trafficservice.RequestEm" +
      "ergency\032!.trafficservice.EmergencyRespon" +
      "se\022C\n\010LiveFeed\022\024.trafficservice.Area\032\037.t" +
      "rafficservice.StreetSituation0\001B+\n\023grpc." +
      "trafficserviceB\022TrafficServiceImplP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_trafficservice_RequestEmergency_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_trafficservice_RequestEmergency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficservice_RequestEmergency_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_trafficservice_EmergencyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_trafficservice_EmergencyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficservice_EmergencyResponse_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_trafficservice_Area_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_trafficservice_Area_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficservice_Area_descriptor,
        new java.lang.String[] { "IntArea", });
    internal_static_trafficservice_StreetSituation_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_trafficservice_StreetSituation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficservice_StreetSituation_descriptor,
        new java.lang.String[] { "TextSituation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
