// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trafficService.proto

package grpc.trafficservice;

public final class TrafficServiceImpl {
  private TrafficServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficservice_RequestEmergency_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficservice_RequestEmergency_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficservice_EmergencyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficservice_EmergencyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficservice_Area_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficservice_Area_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficservice_StreetSituation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficservice_StreetSituation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficservice_Video_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficservice_Video_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficservice_WarningResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficservice_WarningResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficservice_Alert_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficservice_Alert_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficservice_UserAlertRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficservice_UserAlertRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficservice_UserAlertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficservice_UserAlertResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024trafficService.proto\022\016trafficservice\"#" +
      "\n\020RequestEmergency\022\017\n\007message\030\001 \001(\t\"!\n\021E" +
      "mergencyResponse\022\014\n\004text\030\001 \001(\t\"\027\n\004Area\022\017" +
      "\n\007intArea\030\001 \001(\005\"(\n\017StreetSituation\022\025\n\rte" +
      "xtSituation\030\001 \001(\t\"!\n\005Video\022\030\n\020pedestrian" +
      "Number\030\001 \001(\005\"\037\n\017WarningResponse\022\014\n\004text\030" +
      "\001 \001(\t\"*\n\005Alert\022\020\n\010location\030\001 \001(\t\022\017\n\007mess" +
      "age\030\002 \001(\t\"8\n\020UserAlertRequest\022$\n\005alert\030\001" +
      " \001(\0132\025.trafficservice.Alert\"#\n\021UserAlert" +
      "Response\022\016\n\006result\030\001 \001(\t2\332\002\n\016trafficServ" +
      "ice\022T\n\rsendEmergency\022 .trafficservice.Re" +
      "questEmergency\032!.trafficservice.Emergenc" +
      "yResponse\022C\n\010LiveFeed\022\024.trafficservice.A" +
      "rea\032\037.trafficservice.StreetSituation0\001\022U" +
      "\n\031CalculatePedestrianNumber\022\025.trafficser" +
      "vice.Video\032\037.trafficservice.WarningRespo" +
      "nse(\001\022V\n\013StreetAlert\022 .trafficservice.Us" +
      "erAlertRequest\032!.trafficservice.UserAler" +
      "tResponse(\0010\001B+\n\023grpc.trafficserviceB\022Tr" +
      "afficServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_trafficservice_RequestEmergency_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_trafficservice_RequestEmergency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficservice_RequestEmergency_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_trafficservice_EmergencyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_trafficservice_EmergencyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficservice_EmergencyResponse_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_trafficservice_Area_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_trafficservice_Area_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficservice_Area_descriptor,
        new java.lang.String[] { "IntArea", });
    internal_static_trafficservice_StreetSituation_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_trafficservice_StreetSituation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficservice_StreetSituation_descriptor,
        new java.lang.String[] { "TextSituation", });
    internal_static_trafficservice_Video_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_trafficservice_Video_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficservice_Video_descriptor,
        new java.lang.String[] { "PedestrianNumber", });
    internal_static_trafficservice_WarningResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_trafficservice_WarningResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficservice_WarningResponse_descriptor,
        new java.lang.String[] { "Text", });
    internal_static_trafficservice_Alert_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_trafficservice_Alert_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficservice_Alert_descriptor,
        new java.lang.String[] { "Location", "Message", });
    internal_static_trafficservice_UserAlertRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_trafficservice_UserAlertRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficservice_UserAlertRequest_descriptor,
        new java.lang.String[] { "Alert", });
    internal_static_trafficservice_UserAlertResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_trafficservice_UserAlertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficservice_UserAlertResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
