// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trafficService.proto

package grpc.trafficservice;

public interface UserAlertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trafficservice.UserAlertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
