// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trafficService.proto

package grpc.trafficservice;

public interface UserAlertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trafficservice.UserAlertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.trafficservice.Alert alert = 1;</code>
   */
  boolean hasAlert();
  /**
   * <code>.trafficservice.Alert alert = 1;</code>
   */
  grpc.trafficservice.Alert getAlert();
  /**
   * <code>.trafficservice.Alert alert = 1;</code>
   */
  grpc.trafficservice.AlertOrBuilder getAlertOrBuilder();
}
