// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trafficService.proto

package grpc.trafficservice;

public interface VideoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trafficservice.Video)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 pedestrianNumber = 1;</code>
   */
  int getPedestrianNumber();
}
