// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plannerService.proto

package grpc.plannerservice;

public interface DayRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:plannerservice.DayRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.plannerservice.DayRequest.DayOfTheWeek dayOfTheWeek = 1;</code>
   */
  int getDayOfTheWeekValue();
  /**
   * <code>.plannerservice.DayRequest.DayOfTheWeek dayOfTheWeek = 1;</code>
   */
  grpc.plannerservice.DayRequest.DayOfTheWeek getDayOfTheWeek();
}
