// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlannerService.proto

package grpc.plannerservice;

/**
 * Protobuf type {@code plannerservice.DayRequest}
 */
public  final class DayRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:plannerservice.DayRequest)
    DayRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DayRequest.newBuilder() to construct.
  private DayRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DayRequest() {
    dayOfTheWeek_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DayRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            dayOfTheWeek_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.plannerservice.PlannerServiceImpl.internal_static_plannerservice_DayRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.plannerservice.PlannerServiceImpl.internal_static_plannerservice_DayRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.plannerservice.DayRequest.class, grpc.plannerservice.DayRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code plannerservice.DayRequest.DayOfTheWeek}
   */
  public enum DayOfTheWeek
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>MONDAY = 1;</code>
     */
    MONDAY(1),
    /**
     * <code>TUESDAY = 2;</code>
     */
    TUESDAY(2),
    /**
     * <code>WEDNESDAY = 3;</code>
     */
    WEDNESDAY(3),
    /**
     * <code>THURSDAY = 4;</code>
     */
    THURSDAY(4),
    /**
     * <code>FRIDAY = 5;</code>
     */
    FRIDAY(5),
    /**
     * <code>SATURDAY = 6;</code>
     */
    SATURDAY(6),
    /**
     * <code>SUNDAY = 7;</code>
     */
    SUNDAY(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>MONDAY = 1;</code>
     */
    public static final int MONDAY_VALUE = 1;
    /**
     * <code>TUESDAY = 2;</code>
     */
    public static final int TUESDAY_VALUE = 2;
    /**
     * <code>WEDNESDAY = 3;</code>
     */
    public static final int WEDNESDAY_VALUE = 3;
    /**
     * <code>THURSDAY = 4;</code>
     */
    public static final int THURSDAY_VALUE = 4;
    /**
     * <code>FRIDAY = 5;</code>
     */
    public static final int FRIDAY_VALUE = 5;
    /**
     * <code>SATURDAY = 6;</code>
     */
    public static final int SATURDAY_VALUE = 6;
    /**
     * <code>SUNDAY = 7;</code>
     */
    public static final int SUNDAY_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DayOfTheWeek valueOf(int value) {
      return forNumber(value);
    }

    public static DayOfTheWeek forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return MONDAY;
        case 2: return TUESDAY;
        case 3: return WEDNESDAY;
        case 4: return THURSDAY;
        case 5: return FRIDAY;
        case 6: return SATURDAY;
        case 7: return SUNDAY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DayOfTheWeek>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DayOfTheWeek> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DayOfTheWeek>() {
            public DayOfTheWeek findValueByNumber(int number) {
              return DayOfTheWeek.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return grpc.plannerservice.DayRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final DayOfTheWeek[] VALUES = values();

    public static DayOfTheWeek valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DayOfTheWeek(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:plannerservice.DayRequest.DayOfTheWeek)
  }

  public static final int DAYOFTHEWEEK_FIELD_NUMBER = 1;
  private int dayOfTheWeek_;
  /**
   * <code>.plannerservice.DayRequest.DayOfTheWeek dayOfTheWeek = 1;</code>
   */
  public int getDayOfTheWeekValue() {
    return dayOfTheWeek_;
  }
  /**
   * <code>.plannerservice.DayRequest.DayOfTheWeek dayOfTheWeek = 1;</code>
   */
  public grpc.plannerservice.DayRequest.DayOfTheWeek getDayOfTheWeek() {
    @SuppressWarnings("deprecation")
    grpc.plannerservice.DayRequest.DayOfTheWeek result = grpc.plannerservice.DayRequest.DayOfTheWeek.valueOf(dayOfTheWeek_);
    return result == null ? grpc.plannerservice.DayRequest.DayOfTheWeek.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dayOfTheWeek_ != grpc.plannerservice.DayRequest.DayOfTheWeek.UNKNOWN.getNumber()) {
      output.writeEnum(1, dayOfTheWeek_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dayOfTheWeek_ != grpc.plannerservice.DayRequest.DayOfTheWeek.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, dayOfTheWeek_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.plannerservice.DayRequest)) {
      return super.equals(obj);
    }
    grpc.plannerservice.DayRequest other = (grpc.plannerservice.DayRequest) obj;

    boolean result = true;
    result = result && dayOfTheWeek_ == other.dayOfTheWeek_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DAYOFTHEWEEK_FIELD_NUMBER;
    hash = (53 * hash) + dayOfTheWeek_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.plannerservice.DayRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.plannerservice.DayRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.plannerservice.DayRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.plannerservice.DayRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.plannerservice.DayRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.plannerservice.DayRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.plannerservice.DayRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.plannerservice.DayRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.plannerservice.DayRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.plannerservice.DayRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.plannerservice.DayRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.plannerservice.DayRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.plannerservice.DayRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code plannerservice.DayRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:plannerservice.DayRequest)
      grpc.plannerservice.DayRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.plannerservice.PlannerServiceImpl.internal_static_plannerservice_DayRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.plannerservice.PlannerServiceImpl.internal_static_plannerservice_DayRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.plannerservice.DayRequest.class, grpc.plannerservice.DayRequest.Builder.class);
    }

    // Construct using grpc.plannerservice.DayRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      dayOfTheWeek_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.plannerservice.PlannerServiceImpl.internal_static_plannerservice_DayRequest_descriptor;
    }

    @java.lang.Override
    public grpc.plannerservice.DayRequest getDefaultInstanceForType() {
      return grpc.plannerservice.DayRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.plannerservice.DayRequest build() {
      grpc.plannerservice.DayRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.plannerservice.DayRequest buildPartial() {
      grpc.plannerservice.DayRequest result = new grpc.plannerservice.DayRequest(this);
      result.dayOfTheWeek_ = dayOfTheWeek_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.plannerservice.DayRequest) {
        return mergeFrom((grpc.plannerservice.DayRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.plannerservice.DayRequest other) {
      if (other == grpc.plannerservice.DayRequest.getDefaultInstance()) return this;
      if (other.dayOfTheWeek_ != 0) {
        setDayOfTheWeekValue(other.getDayOfTheWeekValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.plannerservice.DayRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.plannerservice.DayRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int dayOfTheWeek_ = 0;
    /**
     * <code>.plannerservice.DayRequest.DayOfTheWeek dayOfTheWeek = 1;</code>
     */
    public int getDayOfTheWeekValue() {
      return dayOfTheWeek_;
    }
    /**
     * <code>.plannerservice.DayRequest.DayOfTheWeek dayOfTheWeek = 1;</code>
     */
    public Builder setDayOfTheWeekValue(int value) {
      dayOfTheWeek_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.plannerservice.DayRequest.DayOfTheWeek dayOfTheWeek = 1;</code>
     */
    public grpc.plannerservice.DayRequest.DayOfTheWeek getDayOfTheWeek() {
      @SuppressWarnings("deprecation")
      grpc.plannerservice.DayRequest.DayOfTheWeek result = grpc.plannerservice.DayRequest.DayOfTheWeek.valueOf(dayOfTheWeek_);
      return result == null ? grpc.plannerservice.DayRequest.DayOfTheWeek.UNRECOGNIZED : result;
    }
    /**
     * <code>.plannerservice.DayRequest.DayOfTheWeek dayOfTheWeek = 1;</code>
     */
    public Builder setDayOfTheWeek(grpc.plannerservice.DayRequest.DayOfTheWeek value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      dayOfTheWeek_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.plannerservice.DayRequest.DayOfTheWeek dayOfTheWeek = 1;</code>
     */
    public Builder clearDayOfTheWeek() {
      
      dayOfTheWeek_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:plannerservice.DayRequest)
  }

  // @@protoc_insertion_point(class_scope:plannerservice.DayRequest)
  private static final grpc.plannerservice.DayRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.plannerservice.DayRequest();
  }

  public static grpc.plannerservice.DayRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DayRequest>
      PARSER = new com.google.protobuf.AbstractParser<DayRequest>() {
    @java.lang.Override
    public DayRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DayRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DayRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DayRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.plannerservice.DayRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

