// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plannerService.proto

package grpc.plannerservice;

/**
 * Protobuf type {@code plannerservice.DiningStreetResponse}
 */
public  final class DiningStreetResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:plannerservice.DiningStreetResponse)
    DiningStreetResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DiningStreetResponse.newBuilder() to construct.
  private DiningStreetResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DiningStreetResponse() {
    streetName_ = "";
    isClosed_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DiningStreetResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            streetName_ = s;
            break;
          }
          case 16: {

            isClosed_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.plannerservice.PlannerServiceImpl.internal_static_plannerservice_DiningStreetResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.plannerservice.PlannerServiceImpl.internal_static_plannerservice_DiningStreetResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.plannerservice.DiningStreetResponse.class, grpc.plannerservice.DiningStreetResponse.Builder.class);
  }

  public static final int STREETNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object streetName_;
  /**
   * <code>string streetName = 1;</code>
   */
  public java.lang.String getStreetName() {
    java.lang.Object ref = streetName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      streetName_ = s;
      return s;
    }
  }
  /**
   * <code>string streetName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStreetNameBytes() {
    java.lang.Object ref = streetName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      streetName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISCLOSED_FIELD_NUMBER = 2;
  private boolean isClosed_;
  /**
   * <code>bool isClosed = 2;</code>
   */
  public boolean getIsClosed() {
    return isClosed_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStreetNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, streetName_);
    }
    if (isClosed_ != false) {
      output.writeBool(2, isClosed_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStreetNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, streetName_);
    }
    if (isClosed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isClosed_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.plannerservice.DiningStreetResponse)) {
      return super.equals(obj);
    }
    grpc.plannerservice.DiningStreetResponse other = (grpc.plannerservice.DiningStreetResponse) obj;

    boolean result = true;
    result = result && getStreetName()
        .equals(other.getStreetName());
    result = result && (getIsClosed()
        == other.getIsClosed());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STREETNAME_FIELD_NUMBER;
    hash = (53 * hash) + getStreetName().hashCode();
    hash = (37 * hash) + ISCLOSED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsClosed());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.plannerservice.DiningStreetResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.plannerservice.DiningStreetResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.plannerservice.DiningStreetResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.plannerservice.DiningStreetResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.plannerservice.DiningStreetResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.plannerservice.DiningStreetResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.plannerservice.DiningStreetResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.plannerservice.DiningStreetResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.plannerservice.DiningStreetResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.plannerservice.DiningStreetResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.plannerservice.DiningStreetResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.plannerservice.DiningStreetResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.plannerservice.DiningStreetResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code plannerservice.DiningStreetResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:plannerservice.DiningStreetResponse)
      grpc.plannerservice.DiningStreetResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.plannerservice.PlannerServiceImpl.internal_static_plannerservice_DiningStreetResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.plannerservice.PlannerServiceImpl.internal_static_plannerservice_DiningStreetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.plannerservice.DiningStreetResponse.class, grpc.plannerservice.DiningStreetResponse.Builder.class);
    }

    // Construct using grpc.plannerservice.DiningStreetResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      streetName_ = "";

      isClosed_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.plannerservice.PlannerServiceImpl.internal_static_plannerservice_DiningStreetResponse_descriptor;
    }

    @java.lang.Override
    public grpc.plannerservice.DiningStreetResponse getDefaultInstanceForType() {
      return grpc.plannerservice.DiningStreetResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.plannerservice.DiningStreetResponse build() {
      grpc.plannerservice.DiningStreetResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.plannerservice.DiningStreetResponse buildPartial() {
      grpc.plannerservice.DiningStreetResponse result = new grpc.plannerservice.DiningStreetResponse(this);
      result.streetName_ = streetName_;
      result.isClosed_ = isClosed_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.plannerservice.DiningStreetResponse) {
        return mergeFrom((grpc.plannerservice.DiningStreetResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.plannerservice.DiningStreetResponse other) {
      if (other == grpc.plannerservice.DiningStreetResponse.getDefaultInstance()) return this;
      if (!other.getStreetName().isEmpty()) {
        streetName_ = other.streetName_;
        onChanged();
      }
      if (other.getIsClosed() != false) {
        setIsClosed(other.getIsClosed());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.plannerservice.DiningStreetResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.plannerservice.DiningStreetResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object streetName_ = "";
    /**
     * <code>string streetName = 1;</code>
     */
    public java.lang.String getStreetName() {
      java.lang.Object ref = streetName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        streetName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string streetName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStreetNameBytes() {
      java.lang.Object ref = streetName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        streetName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string streetName = 1;</code>
     */
    public Builder setStreetName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      streetName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string streetName = 1;</code>
     */
    public Builder clearStreetName() {
      
      streetName_ = getDefaultInstance().getStreetName();
      onChanged();
      return this;
    }
    /**
     * <code>string streetName = 1;</code>
     */
    public Builder setStreetNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      streetName_ = value;
      onChanged();
      return this;
    }

    private boolean isClosed_ ;
    /**
     * <code>bool isClosed = 2;</code>
     */
    public boolean getIsClosed() {
      return isClosed_;
    }
    /**
     * <code>bool isClosed = 2;</code>
     */
    public Builder setIsClosed(boolean value) {
      
      isClosed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isClosed = 2;</code>
     */
    public Builder clearIsClosed() {
      
      isClosed_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:plannerservice.DiningStreetResponse)
  }

  // @@protoc_insertion_point(class_scope:plannerservice.DiningStreetResponse)
  private static final grpc.plannerservice.DiningStreetResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.plannerservice.DiningStreetResponse();
  }

  public static grpc.plannerservice.DiningStreetResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DiningStreetResponse>
      PARSER = new com.google.protobuf.AbstractParser<DiningStreetResponse>() {
    @java.lang.Override
    public DiningStreetResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DiningStreetResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DiningStreetResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DiningStreetResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.plannerservice.DiningStreetResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

