// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plannerService.proto

package grpc.plannerservice;

public interface DiningStreetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:plannerservice.DiningStreetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string streetName = 1;</code>
   */
  java.lang.String getStreetName();
  /**
   * <code>string streetName = 1;</code>
   */
  com.google.protobuf.ByteString
      getStreetNameBytes();

  /**
   * <code>bool isClosed = 2;</code>
   */
  boolean getIsClosed();
}
