// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plannerService.proto

package grpc.plannerservice;

public interface DiningStreetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:plannerservice.DiningStreetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isClosed = 1;</code>
   */
  boolean getIsClosed();
}
