// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plannerService.proto

package grpc.plannerservice;

public final class PlannerServiceImpl {
  private PlannerServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_plannerservice_DayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_plannerservice_DayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_plannerservice_StreetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_plannerservice_StreetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_plannerservice_TimeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_plannerservice_TimeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_plannerservice_DiningStreetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_plannerservice_DiningStreetResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024plannerService.proto\022\016plannerservice\"\304" +
      "\001\n\nDayRequest\022=\n\014dayOfTheWeek\030\001 \001(\0162\'.pl" +
      "annerservice.DayRequest.DayOfTheWeek\"w\n\014" +
      "DayOfTheWeek\022\013\n\007UNKNOWN\020\000\022\n\n\006MONDAY\020\001\022\013\n" +
      "\007TUESDAY\020\002\022\r\n\tWEDNESDAY\020\003\022\014\n\010THURSDAY\020\004\022" +
      "\n\n\006FRIDAY\020\005\022\014\n\010SATURDAY\020\006\022\n\n\006SUNDAY\020\007\"!\n" +
      "\016StreetResponse\022\017\n\007message\030\001 \001(\t\"\033\n\013Time" +
      "Request\022\014\n\004time\030\001 \001(\002\"(\n\024DiningStreetRes" +
      "ponse\022\020\n\010isClosed\030\001 \001(\0102\277\001\n\016PlannerServi" +
      "ce\022T\n\024GetPedestrianStreets\022\032.plannerserv" +
      "ice.DayRequest\032\036.plannerservice.StreetRe" +
      "sponse0\001\022W\n\020GetDiningStreets\022\033.plannerse" +
      "rvice.TimeRequest\032$.plannerservice.Dinin" +
      "gStreetResponse0\001B+\n\023grpc.plannerservice" +
      "B\022PlannerServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_plannerservice_DayRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_plannerservice_DayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_plannerservice_DayRequest_descriptor,
        new java.lang.String[] { "DayOfTheWeek", });
    internal_static_plannerservice_StreetResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_plannerservice_StreetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_plannerservice_StreetResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_plannerservice_TimeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_plannerservice_TimeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_plannerservice_TimeRequest_descriptor,
        new java.lang.String[] { "Time", });
    internal_static_plannerservice_DiningStreetResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_plannerservice_DiningStreetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_plannerservice_DiningStreetResponse_descriptor,
        new java.lang.String[] { "IsClosed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
