// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlannerService.proto

package grpc.plannerservice;

public interface StreetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:plannerservice.StreetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isClosed = 1;</code>
   */
  boolean getIsClosed();
}
