// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plannerService.proto

package grpc.plannerservice;

public interface StreetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:plannerservice.StreetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
