// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plannerService.proto

package grpc.plannerservice;

public interface TimeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:plannerservice.TimeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float time = 1;</code>
   */
  float getTime();
}
